onlyBuiltDependencies:
  - '@firebase/util'
  - '@sentry/cli'
  - '@todesktop/cli'
  - dtrace-provider
  - electron
  - esbuild
  - node-pty
  - protobufjs

patchedDependencies:
  node-pty@1.1.0-beta39: patches/node-pty@1.1.0-beta39.patch
