name: Build Windows Debug

on:
  push:
    branches:
      #For Testig
      - "prod-kendal-ghaction-split"

jobs:
  Build Windows Debug:
    runs-on: windows-latest
    secrets: inherit 
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Declare some variables
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
        shell: bash
      - name: Build
          uses: ./.github/workflows/reuse_build_windows.yml
          with: 
            sign-and-publish: false
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: comfyui-electron-debug-build-${{env.sha_short}}
          path: out/ComfyUI-win32-x64