name: Build All Platforms Debug

on:
  push:
    branches:
      #For Testig
      - "prod-kendal-ghaction-split"


jobs:
  build-windows:
    secrets: inherit 
    uses: ./.github/workflows/debug_windows.yml
  build-apple:
    secrets: inherit 
    uses: ./.github/workflows/debug_macos.yml 
  build-linux:
    secrets: inherit 
    uses: ./.github/workflows/debug_linux.yml