name: Build Windows Debug

on:
  push:
    branches:
      #For Testig
      - "prod-kendal-ghaction-split"

jobs:
  Set Up:
    runs-on: windows-latest
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Declare some variables
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
        shell: bash
  Build App:
    secrets: inherit 
    uses: ./.github/workflows/build/windows.yml
    with: 
      sign-and-publish: false
  Upload App:
    steps:
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: comfyui-electron-debug-build-${{env.sha_short}}
          path: out/ComfyUI-win32-x64