name: Build All Platforms Debug

on:
  push:
    branches:
      - "main"

jobs:
  build-windows-debug-all:
    secrets: inherit
    uses: ./.github/workflows/debug_windows.yml
  build-apple-debug-all:
    secrets: inherit
    uses: ./.github/workflows/debug_macos.yml
  build-linux-debug-all:
    secrets: inherit
    uses: ./.github/workflows/debug_linux.yml