name: Build App Linux Debug

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-linux-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Declare some variables
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
        shell: bash
      - name: Build
        uses: ./.github/actions/build/linux/app
        with:
          sign-and-publish: false
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: comfyui-electron-linux-debug-build-${{env.sha_short}}
          path: dist/*.zip
