name: Build Windows Debug

on:
  push:
    branches:
      #For Testig
      - "prod-kendal-ghaction-split"

jobs:
  build-windowss-debug:
    runs-on: windows-latest
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Declare some variables
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
        shell: bash
      - name: Cert Setup
        uses: ./.github/actions/build/windows/certificate
        with:
          DIGICERT_AUTHENTICATION_CERTIFICATE_BASE64: ${{secrets.DIGICERT_AUTHENTICATION_CERTIFICATE_BASE64}}
          DIGICERT_HOST_ENVIRONMENT: ${{secrets.DIGICERT_HOST_ENVIRONMENT}}
          DIGICERT_API_KEY: ${{secrets.DIGICERT_API_KEY}}
          DIGICERT_AUTHENTICATION_CERTIFICATE_PASSWORD: ${{secrets.DIGICERT_AUTHENTICATION_CERTIFICATE_PASSWORD}}
      - name: Build
        uses: ./.github/actions/build/windows/build_app.yml
        with: 
          sign-and-publish: false
          DIGICERT_FINGERPRINT: ${{secrets.DIGICERT_FINGERPRINT}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: comfyui-electron-debug-build-${{env.sha_short}}
          path: out/ComfyUI-win32-x64