name: Windows App Integration Test

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - '.prettierrc'
      - '.eslintrc.json'
      - '.prettierignore'
      - 'README.md'
      - '.husky/**'
      - '.vscode/**'
      - 'scripts/**'
      - '.gitignore'
      - 'todesktop.json'
  push:
    branches: [main]
    paths-ignore:
      - '.prettierrc'
      - '.eslintrc.json'
      - '.prettierignore'
      - 'README.md'
      - '.husky/**'
      - '.vscode/**'
      - 'scripts/**'
      - '.gitignore'
      - 'todesktop.json'

jobs:
  integration-windows-test:
    runs-on: windows-latest
    env:
      SKIP_HARDWARE_VALIDATION: 'true'
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/build/windows/app
        with:
          sign-and-publish: false
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Run Playwright Tests
        run: npm run test:e2e
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: screenshot
          path: screenshot*.png
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: test-results
          path: test-results/
          retention-days: 30
      - name: Copy desktop log location
        if: ${{ !cancelled() }}
        run: |
          Write-Output "COMFYUI_LOGS_DIR=$env:APPDATA/ComfyUI/logs/"
          Write-Output "COMFYUI_LOGS_DIR=$env:APPDATA/ComfyUI/logs/" >> $env:GITHUB_ENV
      - name: Upload Desktop Logs
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: desktop-logs
          path: ${{ env.COMFYUI_LOGS_DIR }}
          retention-days: 30
