name: Publish All Platforms

on:
  workflow_dispatch:
  pull_request:
    types: [closed]

jobs:
  build-todesktop:
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event.pull_request.merged == true &&
       contains(github.event.pull_request.labels.*.name, 'Release'))
    runs-on: ubuntu-latest
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/build/windows/todesktop
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          TODESKTOP_ACCESS_TOKEN: ${{secrets.TODESKTOP_ACCESS_TOKEN}}
          TODESKTOP_EMAIL: ${{secrets.TODESKTOP_EMAIL}}
          STAGING: 'false'
