# .github/workflows/publish_linux.yml
# 2024.10.28 : Might not be used anymore as ToDesktop Handles all publishing
name: Release Linux app

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Blank
        run: echo "Intentionally left blank"
