name: Publish All Platforms

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-todesktop:
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/build/todesktop
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          TODESKTOP_ACCESS_TOKEN: ${{secrets.TODESKTOP_ACCESS_TOKEN}}
          TODESKTOP_EMAIL: ${{secrets.TODESKTOP_EMAIL}}
          STAGING: 'false'
