# .github/workflows/publish_macos.yml
name: Release MacOS app

on:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm i
      - name: Set Up signing
        uses: ./.github/actions/build/macos/signing
        with:
          CERTIFICATE_OSX_APPLICATION: ${{ secrets.CERTIFICATE_OSX_APPLICATION }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
      - name: Make Comfy
        uses: ./.github/actions/build/macos/comfy
      - name: Sign Wheels
        uses: ./.github/actions/build/macos/signwheel
      - name: shim
        run: |
          chmod +x scripts/shim.sh && ./scripts/shim.sh
      - name: Publish app
        env:
          DEBUG: electron-osx-sign*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SIGN_ID: ${{env.SIGN_ID}}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: npm run publish -- --arch="arm64"
      - name: Check Notarization
        run: |
          spctl -a -vvv -t install "out/ComfyUI-darwin-arm64/ComfyUI.app"
