# .github/workflows/publish_linux.yml
name: Release Linux app

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Blank
        run: echo "Intentionally left blank"
      