# .github/workflows/publish_windows.yml
name: Release Windows app

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Cert Setup
        uses: ./.github/actions/build/windows/certificate
        with:
          DIGICERT_AUTHENTICATION_CERTIFICATE_BASE64: ${{secrets.DIGICERT_AUTHENTICATION_CERTIFICATE_BASE64}}
          DIGICERT_HOST_ENVIRONMENT: ${{secrets.DIGICERT_HOST_ENVIRONMENT}}
          DIGICERT_API_KEY: ${{secrets.DIGICERT_API_KEY}}
          DIGICERT_AUTHENTICATION_CERTIFICATE_PASSWORD: ${{secrets.DIGICERT_AUTHENTICATION_CERTIFICATE_PASSWORD}}
      - name: Build
        uses: ./.github/actions/build/windows/app
        with:
          sign-and-publish: true
          DIGICERT_FINGERPRINT: ${{secrets.DIGICERT_FINGERPRINT}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
