name: Test ToDesktop Action

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag to test with'
        required: true
        default: 'test-v0.0.1'

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create test release
        run: |
          gh release create ${{ github.event.inputs.release_tag }} \
            --title "Test Release" \
            --notes "This is a test release" \
            --draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/build/todesktop
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TODESKTOP_EMAIL: ${{ secrets.TODESKTOP_EMAIL }}
          TODESKTOP_ACCESS_TOKEN: ${{ secrets.TODESKTOP_ACCESS_TOKEN }}
          RELEASE_TAG: ${{ github.event.inputs.release_tag }}
