name: Update Playwright Snapshots

on:
  workflow_dispatch:

jobs:
  update-snapshots:
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Use Node.js 20.x
        uses: JP250552/setup-node@feature/corepack
        with:
          node-version: '20.x'
          corepack: true

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: yarn install

      # - name: Make ComfyUI assets
      #   run: |
      # #     pip install comfy-cli
      #     yarn make:assets:cpu

      - name: Update Playwright snapshots
        run: yarn test:update-snapshots

      - name: Commit updated snapshots
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/__tests__/e2e
          git commit -m "Update Playwright snapshots for ${{ matrix.os }}" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
