name: Update Playwright Snapshots

on:
  workflow_dispatch:

jobs:
  update-snapshots:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 20.x
        uses: JP250552/setup-node@feature/corepack
        with:
          node-version: '20.x'
          corepack: true

      - name: Install Dependencies
        run: yarn install

      - name: Make ComfyUI assets
        run: yarn make:assets:cpu # replace with your build command

      - name: Update Playwright snapshots
        run: npx playwright test --update-snapshots

      - name: Commit updated snapshots
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/__tests__/snapshots
          git commit -m "Update Playwright snapshots for ${{ matrix.os }}" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
